#pragma once
#include "rust/cxx.h"
#include <cstdint>

namespace pesffi {

struct ObjectSnapshot; // shared structs generated by cxx (src/engine.rs)
struct PathInfo;
struct BrotherColor;
struct ColorBlockInfo;
struct StitchData;

void set_resource_path(rust::Str path);

void new_document();
void set_hoop_size_mm(float w, float h);
float get_hoop_width_mm();
float get_hoop_height_mm();

bool load_ppes(rust::Slice<const uint8_t> data);
bool import_pes(rust::Slice<const uint8_t> data);
bool import_svg(rust::Slice<const uint8_t> data);

int32_t get_object_count();
ObjectSnapshot get_object_snapshot(int32_t index);
rust::Vec<uint8_t> get_object_image_png(int32_t index);

void translate_object(int32_t index, float dx, float dy);
void scale_object(int32_t index, float sx, float sy);
void set_object_rotation(int32_t index, float degree);
void set_object_visible(int32_t index, bool visible);
void set_object_locked(int32_t index, bool locked);
bool delete_object(int32_t index);
bool duplicate_object(int32_t index);
bool move_object_front(int32_t index);
bool move_object_back(int32_t index);

rust::Vec<uint8_t> export_as(rust::Str format);
rust::Vec<uint8_t> get_thumbnail_png(int32_t wmax, int32_t hmax, int32_t index);

// Ordered stitch segments for the whole document (or one object if idx>=0),
// for the stitch-view layer and the simulator.
StitchData get_stitch_data(int32_t obj_index);

int32_t get_path_count(int32_t obj_index);
PathInfo get_path_info(int32_t obj_index, int32_t path_index);
void set_path_fill_color(int32_t obj_index, int32_t path_index, int32_t brother_index);
void set_path_stroke_color(int32_t obj_index, int32_t path_index, int32_t brother_index);
void set_path_stroke_width(int32_t obj_index, int32_t path_index, float width);
rust::Vec<BrotherColor> get_brother_palette();

rust::Vec<ColorBlockInfo> get_color_blocks(int32_t obj_index);
void set_color_block(int32_t obj_index, int32_t block_index, int32_t brother_index);
bool swap_color_block(int32_t obj_index, int32_t block_index, int32_t dir);
void flip_object(int32_t obj_index, bool horizontal);

rust::String get_parameter_json(int32_t obj_index);
bool update_ppef_text(int32_t obj_index);
bool update_ttf_text(int32_t obj_index);

// op: inset | outset | simplify | unite_next | separate | erase_under | up | down
bool path_op(int32_t obj_index, int32_t path_index, rust::Str op, float value);
bool set_param_num(int32_t obj_index, rust::Str key, float value);
bool set_param_bool(int32_t obj_index, rust::Str key, bool value);
bool set_param_str(int32_t obj_index, rust::Str key, rust::Str value);

} // namespace pesffi
