#pragma once
#include "rust/cxx.h"
#include <cstdint>

namespace pesffi {

struct ObjectSnapshot; // shared structs generated by cxx (src/engine.rs)
struct GroupSnapshot;
struct PathInfo;
struct BrotherColor;
struct ColorBlockInfo;
struct StitchData;
struct PathNode;
struct StitchPoint;
struct StitchBlock;

void set_resource_path(rust::Str path);

void new_document();
void set_hoop_size_mm(float w, float h);
float get_hoop_width_mm();
float get_hoop_height_mm();

bool load_ppes(rust::Slice<const uint8_t> data);
bool import_pes(rust::Slice<const uint8_t> data);
bool import_svg(rust::Slice<const uint8_t> data);

int32_t get_object_count();
ObjectSnapshot get_object_snapshot(int32_t index);
rust::Vec<uint8_t> get_object_image_png(int32_t index);

void translate_object(int32_t index, float dx, float dy);
void scale_object(int32_t index, float sx, float sy);
void set_object_rotation(int32_t index, float degree);
void set_object_visible(int32_t index, bool visible);
void set_object_locked(int32_t index, bool locked);
bool delete_object(int32_t index);
bool duplicate_object(int32_t index);
int32_t add_shape(int32_t shape_index);
rust::String get_object_vector_json(int32_t index);
bool update_svg(int32_t index);
bool move_object_front(int32_t index);
bool move_object_back(int32_t index);
bool move_object_to(int32_t from, int32_t to);

// Layer groups (folder-like organizational metadata over the flat object list).
rust::Vec<GroupSnapshot> get_groups();
int32_t create_group(rust::Str name, int32_t parent_id);
bool rename_group(int32_t id, rust::Str name);
bool delete_group(int32_t id); // ungroup: members revert to ungrouped
bool set_group_collapsed(int32_t id, bool collapsed);
bool set_group_order(int32_t id, int32_t order);
void set_object_group(int32_t index, int32_t group_id); // 0 = remove from group
void set_group_visible(int32_t id, bool visible); // cascades to members
void set_group_locked(int32_t id, bool locked);   // cascades to members

rust::Vec<uint8_t> export_as(rust::Str format);
rust::Vec<uint8_t> get_thumbnail_png(int32_t wmax, int32_t hmax, int32_t index);

// Ordered stitch segments for the whole document (or one object if idx>=0),
// for the stitch-view layer and the simulator.
StitchData get_stitch_data(int32_t obj_index);

int32_t get_path_count(int32_t obj_index);
PathInfo get_path_info(int32_t obj_index, int32_t path_index);
void set_path_fill_color(int32_t obj_index, int32_t path_index, int32_t brother_index);
void set_path_stroke_color(int32_t obj_index, int32_t path_index, int32_t brother_index);
void set_path_stroke_width(int32_t obj_index, int32_t path_index, float width);
rust::Vec<BrotherColor> get_brother_palette();

rust::Vec<ColorBlockInfo> get_color_blocks(int32_t obj_index);
void set_color_block(int32_t obj_index, int32_t block_index, int32_t brother_index);
bool swap_color_block(int32_t obj_index, int32_t block_index, int32_t dir);
void flip_object(int32_t obj_index, bool horizontal);

rust::String get_parameter_json(int32_t obj_index);
bool update_ppef_text(int32_t obj_index);
bool update_ttf_text(int32_t obj_index);

// Path-node editing (PathEdit mode). Nodes are reported/moved in WORLD
// coordinates; the object's display rotation is folded in here.
rust::Vec<PathNode> get_path_nodes(int32_t obj_index, int32_t path_index);
bool move_path_node(int32_t obj_index, int32_t path_index, int32_t node_index,
                    float world_dx, float world_dy);
// Move one bezier control point. cp_slot: 1 = cp1, 2 = cp2 of command cmd_index.
bool move_path_handle(int32_t obj_index, int32_t path_index, int32_t cmd_index,
                      int32_t cp_slot, float world_dx, float world_dy);
// Insert a node on the segment ENTERING anchor node_index (between anchors
// node_index-1 and node_index) at parameter t in (0,1) — de-Casteljau-splits a
// bezier/quad, splits a line linearly.
bool insert_path_node(int32_t obj_index, int32_t path_index, int32_t node_index,
                      float t);
// Delete the anchor command at node_index (refuses moveTo/close or collapsing
// a subpath below 2 anchors).
bool delete_path_node(int32_t obj_index, int32_t path_index, int32_t node_index);
// Convert a node's incoming segment between corner (lineTo) and curve (bezierTo).
// to_curve seeds collinear handles (shape-preserving); !to_curve drops to a line.
bool set_path_node_type(int32_t obj_index, int32_t path_index, int32_t node_index,
                        bool to_curve);

// StitchEdit mode — edits the raw needle points of an object's stitch blocks
// (fillBlocks = kind 0, strokeBlocks = kind 1). Points are reported/moved in
// WORLD coordinates (the object's display rotation is folded in here). Unlike
// PathEdit these are NOT regenerated: the blocks ARE the data.
rust::Vec<StitchBlock> get_stitch_points(int32_t obj_index);
bool move_stitch_point(int32_t obj_index, int32_t kind, int32_t block_index,
                       int32_t point_index, float world_dx, float world_dy);
// Insert a needle point at the midpoint of the segment after point_index (or
// before it when point_index is the last point), mirroring the old StitchEdit.
bool insert_stitch_point(int32_t obj_index, int32_t kind, int32_t block_index,
                         int32_t point_index);
// Insert a needle point at a WORLD position, right after after_index.
bool insert_stitch_point_at(int32_t obj_index, int32_t kind, int32_t block_index,
                            int32_t after_index, float world_x, float world_y);
bool delete_stitch_point(int32_t obj_index, int32_t kind, int32_t block_index,
                         int32_t point_index);

// op: inset | outset | simplify | unite_next | separate | erase_under | up | down
bool path_op(int32_t obj_index, int32_t path_index, rust::Str op, float value);
bool set_param_num(int32_t obj_index, rust::Str key, float value);
bool set_param_bool(int32_t obj_index, rust::Str key, bool value);
bool set_param_str(int32_t obj_index, rust::Str key, rust::Str value);

} // namespace pesffi
