import { useEffect, useMemo, useRef, useState } from "react";
import { Folder, ImageOff, Loader2, Search, X } from "lucide-react";
import { useDocumentStore } from "../state/documentStore";
import { useUiStore, type LibraryKind } from "../state/uiStore";

// คลังแบบ (design library) — the port of the old app's three toolbox dialogs
// (DlgSVG/DlgPES/DlgPPES): browse the category tree from manifest.json, show
// pre-baked thumbnails, click to insert. Payload is generated by
// scripts/build-library.sh into public/library/ (dev) or the CDN (prod,
// VITE_LIBRARY_BASE) — files fetched on demand, same model as the fonts.

const LIBRARY_BASE =
  (import.meta.env.VITE_LIBRARY_BASE as string | undefined) ?? "/library";

interface FileNode {
  type: "file";
  name: string;
  /** repo-relative file URL under the lib root, e.g. "files/Animal/cat.svg" */
  path: string;
  /** thumbnail URL under the lib root; null = bake failed, show placeholder */
  thumb: string | null;
}
interface DirNode {
  type: "directory";
  name: string;
  contents: (FileNode | DirNode)[];
}
interface Manifest {
  generated: string;
  count: number;
  tree: DirNode;
}

const TABS: { key: LibraryKind; label: string }[] = [
  { key: "svg", label: "SVG" },
  { key: "pes", label: "PES" },
  { key: "ppes", label: "แม่แบบ (PPES)" },
];

/** encode each path segment (Thai names, spaces) but keep the slashes */
const encodePath = (p: string) => p.split("/").map(encodeURIComponent).join("/");
const libUrl = (lib: LibraryKind, p: string) =>
  `${LIBRARY_BASE}/${lib}/${encodePath(p)}`;

// manifests are immutable per build — fetch once per lib, share across opens
const manifestCache = new Map<LibraryKind, Promise<Manifest>>();
function fetchManifest(lib: LibraryKind): Promise<Manifest> {
  let p = manifestCache.get(lib);
  if (!p) {
    p = fetch(`${LIBRARY_BASE}/${lib}/manifest.json`).then((r) => {
      if (!r.ok) throw new Error(`manifest ${lib}: HTTP ${r.status}`);
      return r.json() as Promise<Manifest>;
    });
    p.catch(() => manifestCache.delete(lib)); // allow retry after a failure
    manifestCache.set(lib, p);
  }
  return p;
}

/** flat search index: every file with its category path for display */
function flatten(tree: DirNode): { file: FileNode; folder: string }[] {
  const out: { file: FileNode; folder: string }[] = [];
  const rec = (dir: DirNode, crumbs: string[]) => {
    for (const n of dir.contents) {
      if (n.type === "directory") rec(n, [...crumbs, n.name]);
      else out.push({ file: n, folder: crumbs.join(" / ") });
    }
  };
  rec(tree, []);
  return out;
}

const SEARCH_CAP = 200; // grid stays snappy without a virtualizer

export default function LibraryPanel() {
  const lib = useUiStore((s) => s.libraryOpen);
  const setLibraryOpen = useUiStore((s) => s.setLibraryOpen);
  const openBytes = useDocumentStore((s) => s.openBytes);
  const objectCount = useDocumentStore((s) => s.doc?.objects.length ?? 0);

  const [manifest, setManifest] = useState<Manifest | null>(null);
  const [error, setError] = useState<string | null>(null);
  // breadcrumb trail, root first (same model as the old contents_stack)
  const [stack, setStack] = useState<DirNode[]>([]);
  const [query, setQuery] = useState("");
  const [inserting, setInserting] = useState<string | null>(null);
  const searchRef = useRef<HTMLInputElement>(null);

  // load manifest + reset navigation whenever the panel opens / tab changes
  useEffect(() => {
    if (!lib) return;
    setManifest(null);
    setError(null);
    setStack([]);
    setQuery("");
    let stale = false;
    fetchManifest(lib)
      .then((m) => {
        if (stale) return;
        setManifest(m);
        setStack([m.tree]);
      })
      .catch((e) => !stale && setError(String(e)));
    return () => {
      stale = true;
    };
  }, [lib]);

  // Esc closes (matches the app's other overlays)
  useEffect(() => {
    if (!lib) return;
    const onEsc = (e: KeyboardEvent) => {
      if (e.key === "Escape") setLibraryOpen(null);
    };
    window.addEventListener("keydown", onEsc);
    return () => window.removeEventListener("keydown", onEsc);
  }, [lib, setLibraryOpen]);

  const index = useMemo(
    () => (manifest ? flatten(manifest.tree) : []),
    [manifest],
  );
  const results = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return null;
    return index.filter(
      (e) =>
        e.file.name.toLowerCase().includes(q) ||
        e.folder.toLowerCase().includes(q),
    );
  }, [index, query]);

  if (!lib) return null;

  const cwd = stack[stack.length - 1];

  const insert = async (file: FileNode) => {
    if (inserting) return;
    // a PPES template REPLACES the whole document (same as opening a file)
    if (
      lib === "ppes" &&
      objectCount > 0 &&
      !window.confirm(
        "แม่แบบจะแทนที่งานปัจจุบันทั้งหมด ต้องการดำเนินการต่อหรือไม่?",
      )
    )
      return;
    setInserting(file.path);
    try {
      const res = await fetch(libUrl(lib, file.path));
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const bytes = new Uint8Array(await res.arrayBuffer());
      await openBytes(file.name, bytes);
      setLibraryOpen(null);
    } catch (e) {
      setError(`โหลดไฟล์ไม่สำเร็จ: ${e}`);
    } finally {
      setInserting(null);
    }
  };

  const FileCard = ({ file, sub }: { file: FileNode; sub?: string }) => (
    <button
      key={file.path}
      onClick={() => void insert(file)}
      disabled={inserting !== null}
      title={sub ? `${sub} / ${file.name}` : file.name}
      className="group flex flex-col items-center gap-1.5 rounded-lg border border-neutral-200 bg-white p-2 text-center shadow-sm transition hover:border-blue-400 hover:shadow-md disabled:opacity-60"
    >
      <div className="relative flex h-24 w-full items-center justify-center overflow-hidden rounded-md bg-neutral-50">
        {file.thumb ? (
          <img
            src={libUrl(lib, file.thumb)}
            alt={file.name}
            loading="lazy"
            draggable={false}
            className="max-h-full max-w-full object-contain transition group-hover:scale-105"
          />
        ) : (
          <ImageOff size={28} className="text-neutral-300" />
        )}
        {inserting === file.path && (
          <div className="absolute inset-0 flex items-center justify-center bg-white/70">
            <Loader2 size={22} className="animate-spin text-blue-600" />
          </div>
        )}
      </div>
      <div className="w-full truncate text-[11px] leading-tight text-neutral-600">
        {file.name.replace(/\.[^.]+$/, "")}
      </div>
      {sub && (
        <div className="w-full truncate text-[10px] text-neutral-400">{sub}</div>
      )}
    </button>
  );

  return (
    <div
      className="fixed inset-0 z-40 flex items-center justify-center bg-black/40 p-4 backdrop-blur-[2px]"
      onClick={() => setLibraryOpen(null)}
    >
      <div
        className="flex h-[82vh] w-full max-w-4xl flex-col overflow-hidden rounded-xl bg-neutral-50 shadow-2xl ring-1 ring-black/10"
        onClick={(e) => e.stopPropagation()}
      >
        {/* header: title + tabs + search + close */}
        <div className="flex items-center gap-3 border-b border-neutral-200 bg-white px-4 py-2.5">
          <h2 className="text-sm font-semibold text-neutral-800">
            คลังแบบ (Library)
          </h2>
          <div className="flex rounded-lg bg-neutral-100 p-0.5">
            {TABS.map((t) => (
              <button
                key={t.key}
                onClick={() => setLibraryOpen(t.key)}
                className={`rounded-md px-3 py-1 text-xs font-medium transition ${
                  lib === t.key
                    ? "bg-white text-blue-700 shadow-sm"
                    : "text-neutral-500 hover:text-neutral-700"
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>
          <div className="relative ml-auto w-56">
            <Search
              size={14}
              className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 text-neutral-400"
            />
            <input
              ref={searchRef}
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="ค้นหา..."
              className="w-full rounded-md border border-neutral-200 bg-neutral-50 py-1.5 pl-8 pr-7 text-xs outline-none transition focus:border-blue-400 focus:bg-white"
            />
            {query && (
              <button
                onClick={() => {
                  setQuery("");
                  searchRef.current?.focus();
                }}
                className="absolute right-1.5 top-1/2 -translate-y-1/2 rounded p-0.5 text-neutral-400 hover:text-neutral-600"
              >
                <X size={13} />
              </button>
            )}
          </div>
          <button
            onClick={() => setLibraryOpen(null)}
            aria-label="ปิด"
            className="rounded-md p-1.5 text-neutral-400 transition hover:bg-neutral-100 hover:text-neutral-700"
          >
            <X size={18} />
          </button>
        </div>

        {/* breadcrumb (hidden while searching) */}
        {!results && stack.length > 0 && (
          <div className="flex flex-wrap items-center gap-1 border-b border-neutral-200 bg-white/60 px-4 py-1.5 text-xs text-neutral-500">
            {stack.map((d, i) => (
              <span key={i} className="flex items-center gap-1">
                {i > 0 && <span className="text-neutral-300">/</span>}
                <button
                  onClick={() => setStack(stack.slice(0, i + 1))}
                  className={`rounded px-1 py-0.5 transition hover:bg-neutral-100 ${
                    i === stack.length - 1
                      ? "font-medium text-neutral-800"
                      : "hover:text-neutral-700"
                  }`}
                >
                  {i === 0 ? "ทั้งหมด" : d.name}
                </button>
              </span>
            ))}
          </div>
        )}

        {/* body */}
        <div className="flex-1 overflow-y-auto p-4">
          {error && (
            <div className="mb-3 rounded-md border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-600">
              {error}
              <span className="ml-2 text-red-400">
                (ต้องรัน scripts/build-library.sh ก่อน)
              </span>
            </div>
          )}
          {!manifest && !error && (
            <div className="flex h-full items-center justify-center text-neutral-400">
              <Loader2 size={26} className="animate-spin" />
            </div>
          )}

          {/* search results — flat, capped so the grid stays light */}
          {manifest && results && (
            <>
              <div className="mb-2 text-xs text-neutral-500">
                พบ {results.length} รายการ
                {results.length > SEARCH_CAP && ` (แสดง ${SEARCH_CAP} แรก)`}
              </div>
              <div className="grid grid-cols-3 gap-2.5 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6">
                {results.slice(0, SEARCH_CAP).map((e) => (
                  <FileCard key={e.file.path} file={e.file} sub={e.folder} />
                ))}
              </div>
            </>
          )}

          {/* folder browse */}
          {manifest && !results && cwd && (
            <div className="grid grid-cols-3 gap-2.5 sm:grid-cols-4 md:grid-cols-5 lg:grid-cols-6">
              {cwd.contents.map((n) =>
                n.type === "directory" ? (
                  <button
                    key={n.name}
                    onClick={() => setStack([...stack, n])}
                    className="flex flex-col items-center justify-center gap-1.5 rounded-lg border border-neutral-200 bg-white p-2 py-6 shadow-sm transition hover:border-blue-400 hover:shadow-md"
                  >
                    <Folder size={30} className="text-amber-400" />
                    <div className="w-full truncate text-[11px] leading-tight text-neutral-700">
                      {n.name}
                    </div>
                    <div className="text-[10px] text-neutral-400">
                      {n.contents.length} รายการ
                    </div>
                  </button>
                ) : (
                  <FileCard key={n.path} file={n} />
                ),
              )}
            </div>
          )}
        </div>

        {/* footer hint */}
        <div className="border-t border-neutral-200 bg-white px-4 py-1.5 text-[11px] text-neutral-400">
          {lib === "ppes"
            ? "คลิกแม่แบบเพื่อเปิดเป็นงานใหม่ (แทนที่งานปัจจุบัน)"
            : "คลิกแบบที่ต้องการเพื่อแทรกลงในงานปัจจุบัน"}
          {manifest && (
            <span className="ml-2 text-neutral-300">
              · {manifest.count.toLocaleString()} แบบ
            </span>
          )}
        </div>
      </div>
    </div>
  );
}
